/**
 * Headless smoke probe — does not require an Electron head.
 *
 * Per ADR-025 §7 + ADR-026 §10 this script:
 *
 *   1. spawns dotnet (same args as `src/main.ts`);
 *   2. parses stdout for the listening port;
 *   3. polls /api/runtime/status with the startup token;
 *   4. asserts healthy=true && database.ready=true && database.schemaVersion>=1;
 *   5. POSTs /api/inbox to capture a fresh item;
 *   6. asserts response carries a UUIDv7 id and matching content;
 *   7. GETs /api/inbox?limit=10&offset=0 and asserts total>=1 and the
 *      captured id appears as items[0];
 *   8. SIGTERM's the child;
 *   9. exits 0 on success, 1 on failure.
 *
 * Designed for CI runners with no graphics stack; safe to run from any
 * macOS / Linux shell.
 */

import { randomUUID } from "node:crypto";

import { spawnBackend, HEADER_NAME } from "../src/supervisor/spawn-backend.ts";
import { awaitListening } from "../src/supervisor/port-handshake.ts";
import { probeUntilReady } from "../src/supervisor/readiness-probe.ts";
import { shutdownBackend } from "../src/supervisor/shutdown.ts";

/**
 * Per ADR-026 §B2' the inbox identifier is a UUIDv7 generated by
 * Guid.CreateVersion7. The pattern matches the canonical 36-char
 * representation with version nibble = 7 and variant bits = 10xx.
 */
const UUIDV7_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

interface InboxItemSnapshot {
  id: string;
  content: string;
  source: string | null;
  capturedAtUtc: string;
  createdAt: string;
}

interface InboxListPage {
  items: InboxItemSnapshot[];
  total: number;
  limit: number;
  offset: number;
}

async function captureInboxItem(
  baseUrl: string,
  token: string,
  content: string,
): Promise<InboxItemSnapshot> {
  const response = await fetch(`${baseUrl.replace(/\/+$/u, "")}/api/inbox`, {
    method: "POST",
    headers: {
      [HEADER_NAME]: token,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ content, source: "smoke" }),
  });
  if (!response.ok) {
    throw new Error(
      `POST /api/inbox returned ${response.status} ${response.statusText}`,
    );
  }
  const body = (await response.json()) as InboxItemSnapshot;
  if (!UUIDV7_PATTERN.test(body.id)) {
    throw new Error(`POST /api/inbox returned non-UUIDv7 id: '${body.id}'`);
  }
  if (body.content !== content) {
    throw new Error(
      `POST /api/inbox echoed wrong content: expected '${content}', got '${body.content}'`,
    );
  }
  return body;
}

async function listInboxItems(
  baseUrl: string,
  token: string,
): Promise<InboxListPage> {
  const response = await fetch(
    `${baseUrl.replace(/\/+$/u, "")}/api/inbox?limit=10&offset=0`,
    { headers: { [HEADER_NAME]: token } },
  );
  if (!response.ok) {
    throw new Error(
      `GET /api/inbox returned ${response.status} ${response.statusText}`,
    );
  }
  return (await response.json()) as InboxListPage;
}

async function main(): Promise<void> {
  const token = randomUUID();
  // Smoke runs do not stream stdout to console by default — the
  // handshake parser owns the stream and we keep the test output
  // focused on PASS / FAIL.
  const child = spawnBackend({ token, inheritStdio: false });
  console.log(`[smoke] spawned dotnet (pid=${child.pid ?? "?"})`);

  let baseUrl: string | undefined;
  try {
    // Cold `dotnet run` (msbuild restore + JIT) can take ~30s; allow up
    // to 90s for the listening line so CI / first-run scenarios pass.
    const listening = await awaitListening(child, 90_000);
    baseUrl = listening.baseUrl;
    console.log(`[smoke] api listening on ${baseUrl}`);

    const ready = await probeUntilReady({
      baseUrl,
      token,
      intervalMs: 250,
      timeoutMs: 30_000,
    });
    const version = ready.status.database?.schemaVersion ?? "?";
    console.log(
      `[smoke] status ready (schemaVersion=${version}) in ${ready.durationMs}ms`,
    );

    const captureContent = `smoke probe @ ${new Date().toISOString()}`;
    const captured = await captureInboxItem(baseUrl, token, captureContent);
    console.log(`[smoke] inbox capture id=${captured.id}`);

    const page = await listInboxItems(baseUrl, token);
    if (page.total < 1) {
      throw new Error(`GET /api/inbox returned total=${page.total}, expected ≥1`);
    }
    const first = page.items[0];
    if (first === undefined) {
      throw new Error("GET /api/inbox returned no items after a successful POST");
    }
    if (first.id !== captured.id) {
      throw new Error(
        `GET /api/inbox first item id '${first.id}' does not match captured id '${captured.id}'`,
      );
    }
    console.log(
      `[smoke] inbox list ok (total=${page.total}, first=${first.id})`,
    );

    console.log("[smoke] PASS");
  } catch (err) {
    console.error(
      `[smoke] FAIL: ${err instanceof Error ? err.message : String(err)}`,
    );
    process.exitCode = 1;
  } finally {
    await shutdownBackend(child, 10_000);
  }
}

void main();

