/**
 * Headless smoke probe — does not require an Electron head.
 *
 * Per ADR-025 §7 + ADR-026 §10 this script:
 *
 *   1. spawns dotnet (same args as `src/main.ts`);
 *   2. parses stdout for the listening port;
 *   3. polls /api/runtime/status with the startup token;
 *   4. asserts healthy=true && database.ready=true && database.schemaVersion>=1;
 *   5. POSTs /api/inbox to capture a fresh item;
 *   6. asserts response carries a UUIDv7 id and matching content;
 *   7. GETs /api/inbox?limit=10&offset=0 and asserts total>=1 and the
 *      captured id appears as items[0];
 *   8. SIGTERM's the child;
 *   9. exits 0 on success, 1 on failure.
 *
 * Designed for CI runners with no graphics stack; safe to run from any
 * macOS / Linux shell.
 */

import { randomUUID } from "node:crypto";

import { spawnBackend, HEADER_NAME } from "../src/supervisor/spawn-backend.js";
import { awaitListening } from "../src/supervisor/port-handshake.js";
import { probeUntilReady } from "../src/supervisor/readiness-probe.js";
import { shutdownBackend } from "../src/supervisor/shutdown.js";

/**
 * Per ADR-026 §B2' the inbox identifier is a UUIDv7 generated by
 * Guid.CreateVersion7. The pattern matches the canonical 36-char
 * representation with version nibble = 7 and variant bits = 10xx.
 */
const UUIDV7_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

interface InboxItemSnapshot {
  id: string;
  content: string;
  source: string | null;
  capturedAtUtc: string;
  createdAt: string;
}

interface InboxListPage {
  items: InboxItemSnapshot[];
  total: number;
  limit: number;
  offset: number;
}

async function captureInboxItem(
  baseUrl: string,
  token: string,
  content: string,
): Promise<InboxItemSnapshot> {
  const response = await fetch(`${baseUrl.replace(/\/+$/u, "")}/api/inbox`, {
    method: "POST",
    headers: {
      [HEADER_NAME]: token,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ content, source: "smoke" }),
  });
  if (!response.ok) {
    throw new Error(
      `POST /api/inbox returned ${response.status} ${response.statusText}`,
    );
  }
  const body = (await response.json()) as InboxItemSnapshot;
  if (!UUIDV7_PATTERN.test(body.id)) {
    throw new Error(`POST /api/inbox returned non-UUIDv7 id: '${body.id}'`);
  }
  if (body.content !== content) {
    throw new Error(
      `POST /api/inbox echoed wrong content: expected '${content}', got '${body.content}'`,
    );
  }
  return body;
}

async function listInboxItems(
  baseUrl: string,
  token: string,
): Promise<InboxListPage> {
  const response = await fetch(
    `${baseUrl.replace(/\/+$/u, "")}/api/inbox?limit=10&offset=0`,
    { headers: { [HEADER_NAME]: token } },
  );
  if (!response.ok) {
    throw new Error(
      `GET /api/inbox returned ${response.status} ${response.statusText}`,
    );
  }
  return (await response.json()) as InboxListPage;
}

interface ChatSession {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

interface ChatSessionListPage {
  items: ChatSession[];
  limit: number;
  offset: number;
}

interface ChatCreateSessionResponse {
  session: ChatSession;
}

interface ChatMessage {
  id: string;
  sessionId: string;
  role: "user" | "assistant";
  content: string;
}

/**
 * Per ADR-032 §决策 G1 the chat surface mirrors inbox's
 * smoke-testable RESTful shape: POST creates a session, GET lists
 * sessions, GET .../messages returns the (empty for a fresh session)
 * history. We stop short of POST .../messages because that path
 * requires a real LLM provider and credentials; the integration tests
 * already cover the streaming end-to-end with a mocked provider.
 */
async function probeChatSessionLifecycle(
  baseUrl: string,
  token: string,
): Promise<void> {
  const root = baseUrl.replace(/\/+$/u, "");
  const createResponse = await fetch(`${root}/api/chat/sessions`, {
    method: "POST",
    headers: { [HEADER_NAME]: token },
  });
  if (!createResponse.ok) {
    throw new Error(
      `POST /api/chat/sessions returned ${createResponse.status} ${createResponse.statusText}`,
    );
  }
  const created = (await createResponse.json()) as ChatCreateSessionResponse;
  if (
    typeof created.session?.id !== "string" ||
    !UUIDV7_PATTERN.test(created.session.id)
  ) {
    throw new Error(
      `POST /api/chat/sessions returned non-UUIDv7 id: '${created.session?.id ?? "<missing>"}'`,
    );
  }
  if (typeof created.session.title !== "string" || created.session.title.length === 0) {
    throw new Error(
      `POST /api/chat/sessions returned empty/missing title (placeholder expected)`,
    );
  }

  const listResponse = await fetch(`${root}/api/chat/sessions?limit=10&offset=0`, {
    headers: { [HEADER_NAME]: token },
  });
  if (!listResponse.ok) {
    throw new Error(
      `GET /api/chat/sessions returned ${listResponse.status} ${listResponse.statusText}`,
    );
  }
  const page = (await listResponse.json()) as ChatSessionListPage;
  if (!Array.isArray(page.items) || page.items.length < 1) {
    throw new Error(
      `GET /api/chat/sessions returned items.length=${page.items?.length ?? "?"}, expected ≥1`,
    );
  }
  const found = page.items.find((s) => s.id === created.session.id);
  if (found === undefined) {
    throw new Error(
      `GET /api/chat/sessions did not include the just-created session id '${created.session.id}'`,
    );
  }

  const messagesResponse = await fetch(
    `${root}/api/chat/sessions/${encodeURIComponent(created.session.id)}/messages`,
    { headers: { [HEADER_NAME]: token } },
  );
  if (!messagesResponse.ok) {
    throw new Error(
      `GET /api/chat/sessions/{id}/messages returned ${messagesResponse.status} ${messagesResponse.statusText}`,
    );
  }
  const messages = (await messagesResponse.json()) as ChatMessage[];
  if (!Array.isArray(messages) || messages.length !== 0) {
    throw new Error(
      `GET /api/chat/sessions/{id}/messages returned non-empty list for a fresh session`,
    );
  }

  console.log(
    `[smoke] chat session ok (id=${created.session.id}, listed=${page.items.length}, history=0)`,
  );
}

interface MemoryEntry {
  id: string;
  content: string;
  scope: string;
  source: string;
  isExplicit: boolean;
  confidence: number;
  sensitivity: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

interface MemoryListPage {
  items: MemoryEntry[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * Per ADR-033 §决策 J1 / §M3 the memory lifecycle smoke probe
 * exercises POST → GET list → PATCH → DELETE → list-default →
 * list-with-soft-deleted, asserting:
 * <list type="bullet">
 *   <item><description>UUIDv7 id on POST.</description></item>
 *   <item><description>Source forced to <c>UserExplicit</c> per §决策 B1.</description></item>
 *   <item><description>PATCH echoes the new content / status.</description></item>
 *   <item><description>DELETE soft-deletes (status=SoftDeleted, deletedAt non-null).</description></item>
 *   <item><description>Default list filters soft-deleted rows out.</description></item>
 *   <item><description><c>includeSoftDeleted=true</c> brings them back.</description></item>
 * </list>
 */
async function probeMemoryLifecycle(
  baseUrl: string,
  token: string,
): Promise<void> {
  const root = baseUrl.replace(/\/+$/u, "");
  const fetchJson = async <T>(
    path: string,
    init?: RequestInit,
  ): Promise<{ status: number; body: T }> => {
    const response = await fetch(`${root}${path}`, {
      ...init,
      headers: {
        [HEADER_NAME]: token,
        ...((init?.body !== undefined && {
          "Content-Type": "application/json",
        }) || {}),
        ...(init?.headers ?? {}),
      },
    });
    if (!response.ok) {
      throw new Error(
        `${init?.method ?? "GET"} ${path} returned ${response.status} ${response.statusText}`,
      );
    }
    const body = (await response.json()) as T;
    return { status: response.status, body };
  };

  const captureContent = `smoke memory @ ${new Date().toISOString()}`;
  const created = (
    await fetchJson<MemoryEntry>("/api/memory", {
      method: "POST",
      body: JSON.stringify({
        content: captureContent,
        scope: "smoke",
        sensitivity: "Sensitive",
      }),
    })
  ).body;
  if (!UUIDV7_PATTERN.test(created.id)) {
    throw new Error(`POST /api/memory returned non-UUIDv7 id: '${created.id}'`);
  }
  if (created.source !== "UserExplicit") {
    throw new Error(
      `POST /api/memory returned source='${created.source}', expected 'UserExplicit' per ADR-033 §决策 B1`,
    );
  }
  if (created.status !== "Active") {
    throw new Error(
      `POST /api/memory returned status='${created.status}', expected 'Active'`,
    );
  }
  if (created.sensitivity !== "Sensitive") {
    throw new Error(
      `POST /api/memory returned sensitivity='${created.sensitivity}', expected 'Sensitive'`,
    );
  }
  if (created.content !== captureContent) {
    throw new Error(
      `POST /api/memory echoed wrong content: expected '${captureContent}', got '${created.content}'`,
    );
  }

  // PATCH content + status. Active → Corrected is a legal transition.
  const patchedContent = `${captureContent} (corrected)`;
  const patched = (
    await fetchJson<MemoryEntry>(
      `/api/memory/${encodeURIComponent(created.id)}`,
      {
        method: "PATCH",
        body: JSON.stringify({
          content: patchedContent,
          scope: null,
          sensitivity: null,
          status: "Corrected",
        }),
      },
    )
  ).body;
  if (patched.id !== created.id) {
    throw new Error(
      `PATCH /api/memory/{id} returned id '${patched.id}' ≠ '${created.id}'`,
    );
  }
  if (patched.content !== patchedContent) {
    throw new Error(
      `PATCH /api/memory/{id} echoed wrong content: expected '${patchedContent}', got '${patched.content}'`,
    );
  }
  if (patched.status !== "Corrected") {
    throw new Error(
      `PATCH /api/memory/{id} returned status='${patched.status}', expected 'Corrected'`,
    );
  }

  // DELETE → soft-delete. Server returns the deleted entry so we can
  // confirm deletedAt got stamped without an extra GET.
  const deleted = (
    await fetchJson<MemoryEntry>(
      `/api/memory/${encodeURIComponent(created.id)}`,
      { method: "DELETE" },
    )
  ).body;
  if (deleted.status !== "SoftDeleted") {
    throw new Error(
      `DELETE /api/memory/{id} returned status='${deleted.status}', expected 'SoftDeleted'`,
    );
  }
  if (deleted.deletedAt === null) {
    throw new Error(
      `DELETE /api/memory/{id} returned deletedAt=null; expected an ISO timestamp`,
    );
  }

  // Default list — soft-deleted rows are hidden.
  const liveList = (
    await fetchJson<MemoryListPage>(`/api/memory?limit=100&offset=0`)
  ).body;
  if (liveList.items.some((item) => item.id === created.id)) {
    throw new Error(
      `GET /api/memory (default) included soft-deleted id '${created.id}'`,
    );
  }

  // includeSoftDeleted=true brings it back.
  const fullList = (
    await fetchJson<MemoryListPage>(
      `/api/memory?limit=100&offset=0&includeSoftDeleted=true`,
    )
  ).body;
  const found = fullList.items.find((item) => item.id === created.id);
  if (found === undefined) {
    throw new Error(
      `GET /api/memory?includeSoftDeleted=true did not include soft-deleted id '${created.id}'`,
    );
  }
  if (found.status !== "SoftDeleted") {
    throw new Error(
      `GET /api/memory?includeSoftDeleted=true returned status='${found.status}' for the deleted entry, expected 'SoftDeleted'`,
    );
  }

  console.log(
    `[smoke] memory lifecycle ok (id=${created.id}, hidden_from_default=true, visible_with_flag=true)`,
  );
}

/**
 * Per ADR-034 §M3 the inbox→memory promotion smoke probe
 * exercises POST /api/inbox → POST /api/inbox/items/{id}/promote-to-memory
 * → GET /api/memory?status=Active, asserting:
 * <list type="bullet">
 *   <item><description>UUIDv7 id on the new ledger row.</description></item>
 *   <item><description>Source pinned to <c>InboxAction</c> per §决策 A1.</description></item>
 *   <item><description>Scope pinned to literal <c>"inbox"</c> per §决策 C1.</description></item>
 *   <item><description><c>isExplicit=true</c>, <c>confidence=1.0</c>, <c>sensitivity="Normal"</c>.</description></item>
 *   <item><description>Content matches the source inbox item verbatim per §决策 B1.</description></item>
 *   <item><description>Re-clicking yields a second distinct ledger row per §决策 F1 (no dedup).</description></item>
 *   <item><description>Both rows visible via GET /api/memory.</description></item>
 * </list>
 */
async function probeInboxToMemoryPromotion(
  baseUrl: string,
  token: string,
): Promise<void> {
  const root = baseUrl.replace(/\/+$/u, "");
  const captureContent = `smoke promote @ ${new Date().toISOString()}`;
  const captured = await captureInboxItem(baseUrl, token, captureContent);

  const promote = async (): Promise<MemoryEntry> => {
    const response = await fetch(
      `${root}/api/inbox/items/${encodeURIComponent(captured.id)}/promote-to-memory`,
      { method: "POST", headers: { [HEADER_NAME]: token } },
    );
    if (!response.ok) {
      throw new Error(
        `POST /api/inbox/items/{id}/promote-to-memory returned ${response.status} ${response.statusText}`,
      );
    }
    return (await response.json()) as MemoryEntry;
  };

  const first = await promote();
  if (!UUIDV7_PATTERN.test(first.id)) {
    throw new Error(
      `promote-to-memory returned non-UUIDv7 id: '${first.id}'`,
    );
  }
  if (first.source !== "InboxAction") {
    throw new Error(
      `promote-to-memory returned source='${first.source}', expected 'InboxAction' per ADR-034 §决策 A1`,
    );
  }
  if (first.scope !== "inbox") {
    throw new Error(
      `promote-to-memory returned scope='${first.scope}', expected 'inbox' per ADR-034 §决策 C1`,
    );
  }
  if (first.isExplicit !== true) {
    throw new Error(
      `promote-to-memory returned isExplicit=${first.isExplicit}, expected true`,
    );
  }
  if (first.confidence !== 1.0) {
    throw new Error(
      `promote-to-memory returned confidence=${first.confidence}, expected 1.0`,
    );
  }
  if (first.sensitivity !== "Normal") {
    throw new Error(
      `promote-to-memory returned sensitivity='${first.sensitivity}', expected 'Normal'`,
    );
  }
  if (first.status !== "Active") {
    throw new Error(
      `promote-to-memory returned status='${first.status}', expected 'Active'`,
    );
  }
  if (first.content !== captureContent) {
    throw new Error(
      `promote-to-memory echoed wrong content: expected '${captureContent}', got '${first.content}'`,
    );
  }

  // Per §决策 F1 V0 does not dedup. Calling promote again must yield a
  // distinct ledger row with the same content.
  const second = await promote();
  if (second.id === first.id) {
    throw new Error(
      `promote-to-memory dedup violation: second call returned id='${second.id}' identical to first — ADR-034 §决策 F1 requires no dedup`,
    );
  }
  if (second.content !== captureContent) {
    throw new Error(
      `promote-to-memory second call echoed wrong content: expected '${captureContent}', got '${second.content}'`,
    );
  }

  // Both rows must be visible via GET /api/memory.
  const listResponse = await fetch(
    `${root}/api/memory?limit=50&offset=0&status=Active`,
    { headers: { [HEADER_NAME]: token } },
  );
  if (!listResponse.ok) {
    throw new Error(
      `GET /api/memory returned ${listResponse.status} ${listResponse.statusText}`,
    );
  }
  const page = (await listResponse.json()) as MemoryListPage;
  const ids = new Set(page.items.map((entry) => entry.id));
  if (!ids.has(first.id) || !ids.has(second.id)) {
    throw new Error(
      `GET /api/memory missing promoted ids (first='${first.id}' present=${ids.has(first.id)}, second='${second.id}' present=${ids.has(second.id)})`,
    );
  }

  console.log(
    `[smoke] inbox→memory promotion ok (inboxId=${captured.id}, ledger1=${first.id}, ledger2=${second.id}, no_dedup=true)`,
  );
}

async function main(): Promise<void> {
  const token = randomUUID();
  // Smoke runs do not stream stdout to console by default — the
  // handshake parser owns the stream and we keep the test output
  // focused on PASS / FAIL.
  const child = spawnBackend({ token, inheritStdio: false });
  console.log(`[smoke] spawned dotnet (pid=${child.pid ?? "?"})`);

  let baseUrl: string | undefined;
  try {
    // Cold `dotnet run` (msbuild restore + JIT) can take ~30s; allow up
    // to 90s for the listening line so CI / first-run scenarios pass.
    const listening = await awaitListening(child, 90_000);
    baseUrl = listening.baseUrl;
    console.log(`[smoke] api listening on ${baseUrl}`);

    const ready = await probeUntilReady({
      baseUrl,
      token,
      intervalMs: 250,
      timeoutMs: 30_000,
    });
    const version = ready.status.database?.schemaVersion ?? "?";
    console.log(
      `[smoke] status ready (schemaVersion=${version}) in ${ready.durationMs}ms`,
    );

    const captureContent = `smoke probe @ ${new Date().toISOString()}`;
    const captured = await captureInboxItem(baseUrl, token, captureContent);
    console.log(`[smoke] inbox capture id=${captured.id}`);

    const page = await listInboxItems(baseUrl, token);
    if (page.total < 1) {
      throw new Error(`GET /api/inbox returned total=${page.total}, expected ≥1`);
    }
    const first = page.items[0];
    if (first === undefined) {
      throw new Error("GET /api/inbox returned no items after a successful POST");
    }
    if (first.id !== captured.id) {
      throw new Error(
        `GET /api/inbox first item id '${first.id}' does not match captured id '${captured.id}'`,
      );
    }
    console.log(
      `[smoke] inbox list ok (total=${page.total}, first=${first.id})`,
    );

    await probeChatSessionLifecycle(baseUrl, token);

    await probeMemoryLifecycle(baseUrl, token);

    await probeInboxToMemoryPromotion(baseUrl, token);

    console.log("[smoke] PASS");
  } catch (err) {
    console.error(
      `[smoke] FAIL: ${err instanceof Error ? err.message : String(err)}`,
    );
    process.exitCode = 1;
  } finally {
    await shutdownBackend(child, 10_000);
  }
}

void main();

