-- ADR-032 §决策 C1 — Chat V0 schema.
--
-- chat_sessions: one row per conversation. Identifier is a UUIDv7
-- generated by the domain factory, stored as TEXT for SQLite. title
-- defaults to a placeholder until the first user turn lands; the
-- AppService then truncates the user's first message to 24 characters
-- and writes it back. updated_at is bumped on every message append so
-- the session list (sorted DESC) keeps the most recently used session
-- at the top.
CREATE TABLE chat_sessions (
    id             TEXT NOT NULL PRIMARY KEY,
    title          TEXT NOT NULL,
    created_at_utc TEXT NOT NULL,
    updated_at_utc TEXT NOT NULL
);

CREATE INDEX ix_chat_sessions_updated_at
    ON chat_sessions (updated_at_utc DESC, id DESC);

-- chat_messages: one row per turn (user or assistant). The system
-- prompt is *not* persisted; per ADR-032 §决策 E1 it is a built-in
-- string the AppService prepends at request time.
--
-- role is stored as a small integer matching ChatRole's ordinal value
-- (1 = user, 2 = assistant); enum stability is enforced by the
-- explicit values in the C# enum. model / prompt_tokens /
-- completion_tokens are NULL for user turns and populated only for
-- assistant turns when the upstream reports them.
CREATE TABLE chat_messages (
    id                TEXT    NOT NULL PRIMARY KEY,
    session_id        TEXT    NOT NULL,
    role              INTEGER NOT NULL,
    content           TEXT    NOT NULL,
    created_at_utc    TEXT    NOT NULL,
    model             TEXT    NULL,
    prompt_tokens     INTEGER NULL,
    completion_tokens INTEGER NULL,
    FOREIGN KEY (session_id) REFERENCES chat_sessions(id)
);

CREATE INDEX ix_chat_messages_session_created
    ON chat_messages (session_id, created_at_utc ASC, id ASC);
