-- ADR-033 §决策 G1 / L1 — Memory Ledger V0 schema.
--
-- memory_entries: one row per long-term memory record. Identifier is a
-- UUIDv7 generated by the domain factory, stored as TEXT for SQLite.
--
-- V0 only persists `source = 1 (UserExplicit)`, `is_explicit = 1`, and
-- `confidence = 1.0` (per ADR-033 §决策 B1). The remaining MemorySource
-- enum values (2 = Conversation, 3 = InboxAction, 4 = Correction) and
-- non-1 confidences are reserved for future inference paths so the
-- schema does not require migration when those land.
--
-- status follows the four-state machine defined in ADR-033 §决策 G1:
--   1 = Active (default)
--   2 = Corrected
--   3 = Archived
--   4 = SoftDeleted
-- deleted_at_utc is non-null only while status = 4. Per PURPOSE.md L3
-- the soft-deleted row is preserved indefinitely in V0; physical 30-day
-- cleanup is deferred to a future ADR.
--
-- sensitivity follows the three-tier vocabulary from ADR-033 §决策 F1
-- and ADR-007:
--   1 = Normal (default)
--   2 = Sensitive
--   3 = HighSensitive
--
-- Per ADR-033 §决策 H1 the interest-profile fields (weight,
-- last_touched_at, decay_policy) are deliberately NOT in this table.
-- ADR-013's implementation will add them via a sidecar table
-- `memory_entries_signals` keyed by entry_id, so we never ALTER this
-- table.
CREATE TABLE memory_entries (
    id              TEXT    NOT NULL PRIMARY KEY,
    content         TEXT    NOT NULL,
    scope           TEXT    NOT NULL DEFAULT 'global',
    source          INTEGER NOT NULL,                 -- MemorySource enum
    is_explicit     INTEGER NOT NULL DEFAULT 1,       -- 0 = false, 1 = true
    confidence      REAL    NOT NULL DEFAULT 1.0,
    sensitivity     INTEGER NOT NULL DEFAULT 1,       -- MemorySensitivity enum
    status          INTEGER NOT NULL DEFAULT 1,       -- MemoryStatus enum
    created_at_utc  TEXT    NOT NULL,
    updated_at_utc  TEXT    NOT NULL,
    deleted_at_utc  TEXT    NULL                      -- non-null iff status = 4
);

-- Memory pane lists are sorted by (status, updated_at_utc DESC, id DESC)
-- so the index covers both the default "exclude soft-deleted" path
-- (which translates to status IN (1,2,3) on the SQL side) and the
-- single-status filter path.
CREATE INDEX ix_memory_entries_status_updated
    ON memory_entries (status, updated_at_utc DESC, id DESC);
